spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nature-portfolio?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Tkrldmlskfk13@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

src-prefix:
  http://localhost:8060/upload/


