spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nature-portfolio?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Tkrldmlskfk13@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      default_batch_size: 100

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8060

src-prefix:
  http://localhost:8060/upload/

aes:
  secret-key: ckdcnffp12345678

jwt:
  secret: rlaejrqodhkehrmvhfptmxmwlatmdtnv
