spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nature-portfolio?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&autoReconnect=true
    username: nature-app
    password: aormfl13@
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

#logging:
#  level:
#    org.hibernate.SQL: debug

aes:
  secret-key: ckdcnffp12345678

jwt:
  secret: rlaejrqodhkehrmvhfptmxmwlatmdtnv

aws:
  s3:
    bucket-name: nature-portfolio
    access-key: AKIA5HDDOS7EDIY5B6YX
    secret-key: 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

front-url-prefix:
  http://dev-nature-portfolio.old-team.net

server:
  port: 8090
