spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nature-portfolio?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: aormfl123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

src-prefix:
  http://nature-portfolio-api.rainy-heaven.com/upload/

custom:
  upload-path: /home/ljs/Works/nature/upload

